import processing.sound.*;

final int ANZAHL_FELDER = 20;
final int FELD_GROESSE = 30;
int leben = 4;
int spielerX = 7; //Spieler Feld X
int spielerY = 3; //Spieler Feld Y
int goodieX;
int goodieY;
int posX;
int posY;
int posGoodieX;
int posGoodieY;
boolean goodie = false;
int score = 0;
int sizeText = 32;
int enemyX;
int enemyY;
int posEnemyX;
int posEnemyY;
boolean play = true;
boolean catchX;
boolean catchY;
PImage toxin;
String webLinkToxin = "https://image.spreadshirtmedia.net/image-server/v1/designs/178540113,width=178,height=178.png";
PImage enemySkin;
String webLinkEnemy = "https://image.spreadshirtmedia.net/image-server/v1/designs/16053430,width=178,height=178.png";
int posToxinX;
int posToxinY;
int toxinX;
int toxinY;
boolean toxinSpawn = false;
boolean invertetMovement = false;
PImage bonusBild;
String webLinkBonus = "https://cdn.staticcrate.com/stock-hd/effects/FootageCrate-Spinning_Gold_Coin_Pixel-prev-full.png";
int bonusX;
int bonusY;
boolean bonusSpawn = false;
int posBonusX;
int posBonusY;
PImage hearth;
String webLinkLives = "https://i.pinimg.com/originals/fc/d0/30/fcd0300deb4fd92735c20a6ea91ec1ca.png";
SoundFile backgroundSound;
SoundFile todesSound;
SoundFile coinSound;
